before_script:
     - export GRADLE_USER_HOME='pwd'/.gradle
     
     
stages:
    - build
    - test
    - deploy


build:
    image: gradle:alpine
    stage: build
    tags:
    - dalfcs_gitlab_docker_ci
    script: 
        - ./gradlew assemble

test:
    stage: test
    image: gradle:alpine
    tags:
    - dalfcs_gitlab_docker_ci
    script:
        - ./gradlew check

deploy_master:
    stage: deploy
    
    tags:
    - dalfcs_gitlab_docker_ci
 
    image: ruby:2.3
 
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$CATME_PROD --api-key=$API_KEY
 
 
    only:
    - master
    
deploy_develop:
    stage: deploy
    
    tags:
    - dalfcs_gitlab_docker_ci
    
    image: ruby:2.3
 
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$CATME_TEST --api-key="beac231e-af64-48dd-9de3-6b4ee5164165"
 
 
    only:
    - develop
